from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton

MenuRu = ReplyKeyboardMarkup(row_width=2, resize_keyboard=True)
Categories = KeyboardButton('🛍️ Категории 🛍️')
Guarantees = KeyboardButton('📃 Гарантии 📃')
Support = KeyboardButton('👨‍💻 Поддержка 👨‍💻')
AboutUs = KeyboardButton('🧩О нас 🧩')
Reviews = KeyboardButton('✔️Отзывы☑️')
MenuRu.add(Categories, Support, Guarantees, AboutUs, Reviews)

AdminMenuRu = ReplyKeyboardMarkup(row_width=2, resize_keyboard=True)
AdminPanel = KeyboardButton('👤Админ-Панель')
AdminMenuRu.add(Categories, Support, Guarantees, AboutUs, Reviews, AdminPanel)

AdminPanelRuIkb = ReplyKeyboardMarkup(row_width=2, resize_keyboard=True)
SendALl = KeyboardButton('📢Создать рассылку')
Users = KeyboardButton('👤Сколько пользователей?💸')
Left = KeyboardButton('⬅В главное меню↩')
AdminPanelRuIkb.add(SendALl)
AdminPanelRuIkb.add(Users)
AdminPanelRuIkb.add(Left)

SendALlRuIkb = ReplyKeyboardMarkup(resize_keyboard=True)
Left_But = KeyboardButton('🚫Отменить рассылку')
SendALlRuIkb.insert(Left_But)

CategoriesRuIkb = InlineKeyboardMarkup(row_width=1)
Fortnite = InlineKeyboardButton('Fortnite', callback_data='fortniteru')
Garant = InlineKeyboardButton('Гаранты', callback_data='garantru')
Bots = InlineKeyboardButton('Боты на заказ', callback_data='botsru')
Ava = InlineKeyboardButton('Аватарки на заказ', callback_data='avaru')
Other = InlineKeyboardButton('Другие приложения', callback_data='otherru')
CategoriesRuIkb.add(Fortnite, Garant, Ava, Other)

OtherRuIkb = InlineKeyboardMarkup(row_width=1)
Spotify = InlineKeyboardButton('Spotify Premium', callback_data='spotifyru')
Youtube = InlineKeyboardButton('YouTube Premium', callback_data='ytru')
DiscordNitro = InlineKeyboardButton('Discord Nitro', callback_data='nitroru')
OtherLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='leftru')
OtherRuIkb.add(Spotify, DiscordNitro, Youtube, OtherLeft)

FortniteRuIkb = InlineKeyboardMarkup(row_width=1)
#Codes = InlineKeyboardButton('🔑Ключи (коды) на скины💁‍♂️', callback_data='codesru')
Gifts = InlineKeyboardButton('🎁Подарки🎁', callback_data='giftsru')
Accaunt = InlineKeyboardButton('👤Аккаунты🧑‍🎤', callback_data='accru')
RandAccant = InlineKeyboardButton('🔀Рандом аккаунты🔄', callback_data='randaccru')
ObmenAccant = InlineKeyboardButton('🔄Обмен аккаунтов👤', callback_data='obmenaccru')
VBucks = InlineKeyboardButton('💸V-bucks на ваш аккаунт✅', callback_data='vbucksru')
Packs = InlineKeyboardButton('🍭Наборы💼', callback_data='packsru')
FortniteLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='leftru')
FortniteRuIkb.add(Packs, VBucks, Gifts, Accaunt, ObmenAccant, RandAccant, FortniteLeft)

SpotifyRuIkb = InlineKeyboardMarkup(row_width=1)
SpotifyIndividual = InlineKeyboardButton('Spotify Individual || 265 руб', callback_data='indru')
SpotifyDuo = InlineKeyboardButton('Spotify Duo || 310 руб', callback_data='duoru')
SpotifyFamily = InlineKeyboardButton('Spotify Family || 340 руб', callback_data='familyru')
SpotifyLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='otherru')
SpotifyRuIkb.add(SpotifyIndividual, SpotifyDuo, SpotifyFamily, SpotifyLeft)

AvaRuIkb = InlineKeyboardMarkup(row_width=1)
Low = InlineKeyboardButton('Аватарки низкого качества', callback_data='avalowru')
Midl = InlineKeyboardButton('Аватарки среднего качества', callback_data='avamidlru')
Perfect = InlineKeyboardButton('Аватарки легендарного качества', callback_data='avalegru')
AvaLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='leftru')
AvaRuIkb.add(Low, Midl, Perfect, AvaLeft)

YouTubeRuIkb = InlineKeyboardMarkup(row_width=1)
YouTubeIndividual = InlineKeyboardButton('YouTube Individual || 210 руб', callback_data='indytru')
YouTubeFamily = InlineKeyboardButton('YouTube Family || 340 руб', callback_data='familyytru')
YouTubeStudent = InlineKeyboardButton('YouTube Student || 190 руб', callback_data='studentytru')
YouTubeLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='otherru')
YouTubeRuIkb.add(YouTubeIndividual, YouTubeFamily, YouTubeStudent, YouTubeLeft)

NitroRuIkb = InlineKeyboardMarkup(row_width=1)
NitroBasic30 = InlineKeyboardButton('Discord Nitro Basic 30 days|| 210 руб', callback_data='nbru30')
NitroBasic365 = InlineKeyboardButton('Discord Nitro Basic 365 days || 1520 руб', callback_data='nbru365')
NitroFull30 = InlineKeyboardButton('Discord Nitro 30 days || 420 руб', callback_data='nru30')
NitroFull365 = InlineKeyboardButton('Discord Nitro 365 days || 3520 руб', callback_data='nru365')
NitroLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='otherru')
NitroRuIkb.add(NitroBasic30, NitroBasic365, NitroFull30, NitroFull365, NitroLeft)

ObmenAccantRuIkb = InlineKeyboardMarkup(row_width=1)
ObmenAccant12 = InlineKeyboardButton('Обмен аккаунтом 12 скинов', callback_data='obmenru12')
ObmenAccant15 = InlineKeyboardButton('Обмен аккаунтом 15 скинов', callback_data='obmenru15')
ObmenAccantLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='fortniteru')
ObmenAccantRuIkb.add(ObmenAccant12, ObmenAccant15, ObmenAccantLeft)

CodesRuIkb = InlineKeyboardMarkup(row_width=1)
code_1 = InlineKeyboardButton('Скин "Бэтмен который смеётся" || 260 руб', callback_data='buy_coderu_1')
code_2 = InlineKeyboardButton('Скин "Человек паук из эпицентра" || 135 руб', callback_data='buy_coderu_2')
code_3 = InlineKeyboardButton('Скин "Возрождённая Харли Квинн" || 170 руб', callback_data='buy_coderu_3')
code_4 = InlineKeyboardButton('Инструмент "Крюк Женщины-Кошки" || 245 руб', callback_data='buy_coderu_4')
code_5 = InlineKeyboardButton('Инструмент "Адамантиевые когти" || 95 руб', callback_data='buy_coderu_5')
code_6 = InlineKeyboardButton('Обёртка "Разработка Старка" || 95 руб', callback_data='buy_coderu_6')
code_7 = InlineKeyboardButton('Граффити "Ших! Ших!" || 95 руб', callback_data='buy_coderu_7')
code_8 = InlineKeyboardButton('Скин "Бэтмен из эпицентра" || 230 руб', callback_data='buy_coderu_8')
code_9 = InlineKeyboardButton('Экран загрузки "Битва за эпицентр" || 95 руб', callback_data='buy_coderu_9')
CodesLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='fortniteru')
CodesRuIkb.add(code_1, code_2, code_3, code_8, code_4, code_5, code_6, code_7, code_9, CodesLeft)

GiftsRuIkb = InlineKeyboardMarkup(row_width=1)
gift_200 = InlineKeyboardButton('Подарок на 200 V-Bucks || 50 руб', callback_data='buy_giftru_200')
gift_500 = InlineKeyboardButton('Подарок на 500 V-Bucks || 110 руб', callback_data='buy_giftru_500')
gift_800 = InlineKeyboardButton('Подарок на 800 V-Bucks || 160 руб', callback_data='buy_giftru_800')
gift_1200 = InlineKeyboardButton('Подарок на 1200 V-Bucks || 255 руб', callback_data='buy_giftru_1200')
gift_1500 = InlineKeyboardButton('Подарок на 1500 V-Bucks || 340 руб', callback_data='buy_giftru_1500')
gift_1800 = InlineKeyboardButton('Подарок на 1800 V-Bucks || 380 руб', callback_data='buy_giftru_1800')
gift_2000 = InlineKeyboardButton('Подарок на 2000 V-Bucks || 420 руб', callback_data='buy_giftru_2000')
gift_2500 = InlineKeyboardButton('Подарок на 2500 V-Bucks || 530 руб', callback_data='buy_giftru_2500')
gift_3000 = InlineKeyboardButton('Подарок на 3000 V-Bucks || 630 руб', callback_data='buy_giftru_3000')
GiftsLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='fortniteru')
GiftsRuIkb.add(gift_200, gift_500, gift_800, gift_1200, gift_1500, gift_1800, gift_2000, gift_2500, gift_3000, GiftsLeft)

AccRuIkb = InlineKeyboardMarkup(row_width=1)
Acc201 = InlineKeyboardButton('Аккаунт 201 скин || 1500 руб', callback_data='acc201')
Acc122 = InlineKeyboardButton('Аккаунт 122 скина || 800 руб', callback_data='acc122')
Acc100 = InlineKeyboardButton('Аккаунт 100 скинов || 800 руб', callback_data='acc100')
Acc89 = InlineKeyboardButton('Аккаунт 89 скинов || 150 руб', callback_data='acc89')
Acc49 = InlineKeyboardButton('Аккаунт 49 скинов || 230 руб', callback_data='acc49')
AccLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='fortniteru')
AccRuIkb.add(Acc201, Acc122, Acc100, Acc89, Acc49, AccLeft) 

RandAccRuIkb = InlineKeyboardMarkup(row_width=1)
Rand_acc_40 = InlineKeyboardButton('Рандом дешевый || 40 руб', callback_data='rand_accru_40')
Rand_acc_140 = InlineKeyboardButton('Рандом средний || 140 руб', callback_data='rand_accru_140')
Rand_acc_250 = InlineKeyboardButton('Рандом дорогой || 250 руб', callback_data='rand_accru_250')
RandAccLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='fortniteru')
RandAccRuIkb.add(Rand_acc_40, Rand_acc_140, Rand_acc_250, RandAccLeft)

VBucksRuIkb = InlineKeyboardMarkup(row_width=1)
VBucks1000 = InlineKeyboardButton('1 000 V-Bucks || 260 руб', callback_data='vbru1000')
VBucks2800 = InlineKeyboardButton('2 800 V-Bucks || 560 руб', callback_data='vbru2800')
VBucks5000 = InlineKeyboardButton('5 000 V-Bucks || 860 руб', callback_data='vbru5000')
VBucks13500 = InlineKeyboardButton('13 500 V-Bucks || 1 960 руб', callback_data='vbru13500')
VBucksLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='fortniteru')
VBucksRuIkb.add(VBucks1000, VBucks2800, VBucks5000, VBucks13500, VBucksLeft)

PacksRuIkb = InlineKeyboardMarkup(row_width=1)
Bioluminescens = InlineKeyboardButton('Набор заданий "Биолюминесценция" || 260 руб', callback_data='bioluminescensru')
TemnuyOgon = InlineKeyboardButton('Комплект "Тёмный огонь" || 430 руб', callback_data='temnyogonru')
Orysheynica = InlineKeyboardButton('Набор "Оружейница Клип" || 465 руб', callback_data='orysheynicaru')
KorolyAndVoins = InlineKeyboardButton('Набор "Короли и воины" || 475 руб', callback_data='korolyandvoinsru')
PrysrakLegend = InlineKeyboardButton('Набор "Призрачные легенды" || 460 руб', callback_data='prysraklegendru')
Otrad = InlineKeyboardButton('Подписка Отряд Fortnite || 420 руб', callback_data='otradru')
PacksLeft = InlineKeyboardButton('⬅ Вернутся ↩', callback_data='fortniteru')
PacksRuIkb.add(Bioluminescens, TemnuyOgon, Orysheynica, PrysrakLegend, KorolyAndVoins, Otrad, PacksLeft)

BuyAccRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернутся ↩', callback_data='accru')
BuyAccRuIkb.add(BuyBut, LeftBut)

BuyRandomRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернутся ↩', callback_data='randaccru')
BuyRandomRuIkb.add(BuyBut, LeftBut)

BuyGiftRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернутся ↩', callback_data='giftsru')
BuyGiftRuIkb.add(BuyBut, LeftBut)

BuyCodeRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернутся ↩', callback_data='codesru')
BuyCodeRuIkb.add(BuyBut, LeftBut)

BuySpotifyRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернутся ↩', callback_data='spotifyru')
BuySpotifyRuIkb.add(BuyBut, LeftBut)

BuyYtRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернутся ↩', callback_data='ytru')
BuyYtRuIkb.add(BuyBut, LeftBut)

BuyNitroRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернутся ↩', callback_data='nitroru')
BuyNitroRuIkb.add(BuyBut, LeftBut)

BuyVbRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернутся ↩', callback_data='vbucksru')
BuyVbRuIkb.add(BuyBut, LeftBut)

BuyObmenRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='🔄 Обменять аккаунт', callback_data='obmenru')
LeftBut = InlineKeyboardButton(text='⬅ Вернутся ↩', callback_data='obmenaccru')
BuyObmenRuIkb.add(BuyBut, LeftBut)

BuyPacksRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернутся ↩', callback_data='packsru')
BuyPacksRuIkb.add(BuyBut, LeftBut)

BuyAvaRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Заказать Аватарку', callback_data='zakazru')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='avaru')
BuyAvaRuIkb.add(BuyBut, LeftBut)