from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton

MenuRu = ReplyKeyboardMarkup(row_width=2, resize_keyboard=True)
Categories = KeyboardButton('🛍️ Категории 🛍️')
Guarantees = KeyboardButton('📃 Гарантии 📃')
Support = KeyboardButton('👨‍💻 Поддержка 👨‍💻')
AboutUs = KeyboardButton('🧩О нас 🧩')
Reviews = KeyboardButton('✔️Отзывы☑️')
MenuRu.add(Categories, Support, Guarantees, AboutUs, Reviews)

AdminMenuRu = ReplyKeyboardMarkup(row_width=2, resize_keyboard=True)
AdminPanel = KeyboardButton('👤Админ-Панель')
AdminMenuRu.add(Categories, Support, Guarantees, AboutUs, Reviews, AdminPanel)

AdminPanelRuIkb = ReplyKeyboardMarkup(row_width=1, resize_keyboard=True)
SendALl = KeyboardButton('📢Создать рассылку')
Left = KeyboardButton('⬅В главное меню↩')
AdminPanelRuIkb.add(SendALl)
AdminPanelRuIkb.add(Left)

SendALlRuIkb = ReplyKeyboardMarkup(resize_keyboard=True)
Left_But = KeyboardButton('🚫Отменить рассылку')
SendALlRuIkb.insert(Left_But)

CategoriesRuIkb = InlineKeyboardMarkup(row_width=1)
Fortnite = InlineKeyboardButton('Fortnite', callback_data='fortniteru')
Other = InlineKeyboardButton('Другие приложения', callback_data='otherru')
CategoriesRuIkb.add(Fortnite, Other)

OtherRuIkb = InlineKeyboardMarkup(row_width=1)
Spotify = InlineKeyboardButton('Spotify Premium', callback_data='spotifyru')
Youtube = InlineKeyboardButton('YouTube Premium', callback_data='ytru')
DiscordNitro = InlineKeyboardButton('Discord Nitro', callback_data='nitroru')
OtherLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='leftru')
OtherRuIkb.add(Spotify, DiscordNitro, Youtube, OtherLeft)

FortniteRuIkb = InlineKeyboardMarkup(row_width=1)
Codes = InlineKeyboardButton('🔑Ключи (коды) на скины💁‍♂️', callback_data='codesru')
Gifts = InlineKeyboardButton('🎁Подарки🎁', callback_data='giftsru')
Accaunt = InlineKeyboardButton('👤Аккаунты🧑‍🎤', callback_data='accru')
RandAccont = InlineKeyboardButton('🔀Рандом аккаунты🔄', callback_data='randaccru')
VBucks = InlineKeyboardButton('💸V-bucks на ваш аккаунт✅', callback_data='vbucksru')
Packs = InlineKeyboardButton('🍭Наборы💼', callback_data='packsru')
FortniteLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='leftru')
FortniteRuIkb.add(Codes, Packs, VBucks, Gifts, Accaunt, RandAccont, FortniteLeft)

SpotifyRuIkb = InlineKeyboardMarkup(row_width=1)
SpotifyIndividual = InlineKeyboardButton('Spotify Individual || 120 грн', callback_data='indru')
SpotifyDuo = InlineKeyboardButton('Spotify Duo || 140 грн', callback_data='duoru')
SpotifyFamily = InlineKeyboardButton('Spotify Family || 150 грн', callback_data='familyru')
SpotifyLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='otherru')
SpotifyRuIkb.add(SpotifyIndividual, SpotifyDuo, SpotifyFamily, SpotifyLeft)

YouTubeRuIkb = InlineKeyboardMarkup(row_width=1)
YouTubeIndividual = InlineKeyboardButton('YouTube Individual || 90 грн', callback_data='indytru')
YouTubeFamily = InlineKeyboardButton('YouTube Family || 140 грн', callback_data='familyytru')
YouTubeStudent = InlineKeyboardButton('YouTube Student || 80 грн', callback_data='studentytru')
YouTubeLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='otherru')
YouTubeRuIkb.add(YouTubeIndividual, YouTubeFamily, YouTubeStudent, YouTubeLeft)

NitroRuIkb = InlineKeyboardMarkup(row_width=1)
NitroBasic30 = InlineKeyboardButton('Discord Nitro Basic 30 days|| 110 грн', callback_data='nbru30')
NitroBasic365 = InlineKeyboardButton('Discord Nitro Basic 365 days || 760 грн', callback_data='nbru365')
NitroFull30 = InlineKeyboardButton('Discord Nitro 30 days || 210 грн', callback_data='nru30')
NitroFull365 = InlineKeyboardButton('Discord Nitro 365 days || 1760 грн', callback_data='nru365')
NitroLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='otherru')
NitroRuIkb.add(NitroBasic30, NitroBasic365, NitroFull30, NitroFull365, NitroLeft)

CodesRuIkb = InlineKeyboardMarkup(row_width=1)
code_1 = InlineKeyboardButton('Скин "Бэтмен который смеётся" | 260 грн', callback_data='buy_coderu_1')
code_2 = InlineKeyboardButton('Скин "Человек паук из эпицентра" | 135 грн', callback_data='buy_coderu_2')
code_3 = InlineKeyboardButton('Скин "Возрождённая Харли Квинн" | 170 грн', callback_data='buy_coderu_3')
code_4 = InlineKeyboardButton('Инструмент "Крюк Женщины-Кошки" | 245 грн', callback_data='buy_coderu_4')
code_5 = InlineKeyboardButton('Инструмент "Адамантиевые когти" | 95 грн', callback_data='buy_coderu_5')
code_6 = InlineKeyboardButton('Обёртка "Разработка Старка" | 95 грн', callback_data='buy_coderu_6')
code_7 = InlineKeyboardButton('Граффити "Ших! Ших!" | 95 грн', callback_data='buy_coderu_7')
code_8 = InlineKeyboardButton('Скин "Бэтмен из эпицентра" | 230 грн', callback_data='buy_coderu_8')
code_9 = InlineKeyboardButton('Экран загрузки "Битва за эпицентр" | 95 грн', callback_data='buy_coderu_9')
CodesLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='fortniteru')
CodesRuIkb.add(code_1, code_2, code_3, code_8, code_4, code_5, code_6, code_7, code_9, CodesLeft)

GiftsRuIkb = InlineKeyboardMarkup(row_width=1)
gift_200 = InlineKeyboardButton('Подарок на 200 В-БАКСОВ | 25 грн', callback_data='buy_giftru_200')
gift_500 = InlineKeyboardButton('Подарок на 500 В-БАКСОВ | 55 грн', callback_data='buy_giftru_500')
gift_800 = InlineKeyboardButton('Подарок на 800 В-БАКСОВ | 80 грн', callback_data='buy_giftru_800')
gift_1200 = InlineKeyboardButton('Подарок на 1200 В-БАКСОВ | 125 грн', callback_data='buy_giftru_1200')
gift_1500 = InlineKeyboardButton('Подарок на 1500 В-БАКСОВ | 155 грн', callback_data='buy_giftru_1500')
gift_1800 = InlineKeyboardButton('Подарок на 2800 В-БАКСОВ | 180 грн', callback_data='buy_giftru_1800')
gift_2000 = InlineKeyboardButton('Подарок на 2000 В-БАКСОВ | 210 грн', callback_data='buy_giftru_2000')
gift_2500 = InlineKeyboardButton('Подарок на 2500 В-БАКСОВ | 260 грн', callback_data='buy_giftru_2500')
gift_3000 = InlineKeyboardButton('Подарок на 3000 В-БАКСОВ | 310 грн', callback_data='buy_giftru_3000')
GiftsLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='fortniteru')
GiftsRuIkb.add(gift_200, gift_500, gift_800, gift_1200, gift_1800, gift_2000, gift_2500, gift_3000, GiftsLeft)

AccRuIkb = InlineKeyboardMarkup(row_width=1)
acc_low = InlineKeyboardButton('Аккаунт 17 скинов Fortnite| 65 грн', callback_data='acc_lowru')
RandAccLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='fortniteru')
AccRuIkb.add(acc_low, RandAccLeft)

RandAccRuIkb = InlineKeyboardMarkup(row_width=1)
Rand_acc_25 = InlineKeyboardButton('Рандом дешевый | 25 грн', callback_data='rand_accru_25')
Rand_acc_65 = InlineKeyboardButton('Рандом средний | 65 грн', callback_data='rand_accru_65')
Rand_acc_120 = InlineKeyboardButton('Рандом дорогой | 120 грн', callback_data='rand_accru_120')
RandAccLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='fortniteru')
RandAccRuIkb.add(Rand_acc_25, Rand_acc_65, Rand_acc_120, RandAccLeft)

VBucksRuIkb = InlineKeyboardMarkup(row_width=1)
VBucks1000 = InlineKeyboardButton('1 000 V-Bucks || 105 грн', callback_data='vbru1000')
VBucks2800 = InlineKeyboardButton('2 800 V-Bucks || 230 грн', callback_data='vbru2800')
VBucks5000 = InlineKeyboardButton('5 000 V-Bucks || 345 грн', callback_data='vbru5000')
VBucks13500 = InlineKeyboardButton('13 500 V-Bucks || 770 грн', callback_data='vbru13500')
VBucksLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='fortniteru')
VBucksRuIkb.add(VBucks1000, VBucks2800, VBucks5000, VBucks13500, VBucksLeft)

PacksRuIkb = InlineKeyboardMarkup(row_width=1)
Bioluminescens = InlineKeyboardButton('Набор заданий "Биолюминесценция" || 120 грн', callback_data='bioluminescensru')
TemnuyOgon = InlineKeyboardButton('Комплект "Тёмный огонь" || 190 грн', callback_data='temnyogonru')
Orysheynica = InlineKeyboardButton('Набор "Оружейница Клип" || 200 грн', callback_data='orysheynicaru')
KorolyAndVoins = InlineKeyboardButton('Набор "Короли и воины" || 250 грн', callback_data='korolyandvoinsru')
Otrad = InlineKeyboardButton('Подписка Отряд Fortnite || 240 грн', callback_data='otradru')
PacksLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='fortniteru')
PacksRuIkb.add(Bioluminescens, TemnuyOgon, Orysheynica, KorolyAndVoins, Otrad, PacksLeft)

BuyAccRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернуться ↩', callback_data='accru')
BuyAccRuIkb.add(BuyBut, LeftBut)

BuyRandomRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернуться ↩', callback_data='randaccru')
BuyRandomRuIkb.add(BuyBut, LeftBut)

BuyGiftRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернуться ↩', callback_data='giftsru')
BuyGiftRuIkb.add(BuyBut, LeftBut)

BuyCodeRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернуться ↩', callback_data='codesru')
BuyCodeRuIkb.add(BuyBut, LeftBut)

BuySpotifyRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернуться ↩', callback_data='spotifyru')
BuySpotifyRuIkb.add(BuyBut, LeftBut)

BuyYtRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернуться ↩', callback_data='ytru')
BuyYtRuIkb.add(BuyBut, LeftBut)

BuyNitroRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернуться ↩', callback_data='nitroru')
BuyNitroRuIkb.add(BuyBut, LeftBut)

BuyVbRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернуться ↩', callback_data='vbucksru')
BuyVbRuIkb.add(BuyBut, LeftBut)

BuyPacksRuIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купить товар', callback_data='buyru')
LeftBut = InlineKeyboardButton(text='⬅ Вернуться ↩', callback_data='packsru')
BuyPacksRuIkb.add(BuyBut, LeftBut)