from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton

MenuUa = ReplyKeyboardMarkup(row_width=2, resize_keyboard=True)
Categories = KeyboardButton('🛍️ Категорії 🛍️')
Guarantees = KeyboardButton('📃 Гарантії 📃')
Support = KeyboardButton('👨‍💻 Підтримка 👨‍💻')
AboutUs = KeyboardButton('🧩Про нас 🧩')
Reviews = KeyboardButton('✔️Відгуки☑️')
MenuUa.add(Categories, Support, Guarantees, AboutUs, Reviews)

AdminMenuUa = ReplyKeyboardMarkup(row_width=2, resize_keyboard=True)
AdminPanel = KeyboardButton('👤Адмін-Панель')
AdminMenuUa.add(Categories, Support, Guarantees, AboutUs, Reviews, AdminPanel)

AdminPanelUaIkb = ReplyKeyboardMarkup(row_width=2, resize_keyboard=True)
SendALl = KeyboardButton('📢Провести розсилку')
Users = KeyboardButton('👤Скільки користувачів?💸')
Left = KeyboardButton('⬅В головне меню↩')
AdminPanelUaIkb.add(SendALl)
AdminPanelUaIkb.add(Users)
AdminPanelUaIkb.add(Left)

SendALlUaIkb = ReplyKeyboardMarkup(resize_keyboard=True)
Left_But = KeyboardButton('🚫Відмінити розсилку')
SendALlUaIkb.insert(Left_But)

CategoriesUaIkb = InlineKeyboardMarkup(row_width=1)
Fortnite = InlineKeyboardButton('Fortnite', callback_data='fortniteua')
Garant = InlineKeyboardButton('Гаранти', callback_data='garantua')
Bots = InlineKeyboardButton('Боти на заказ', callback_data='botsua')
Ava = InlineKeyboardButton('Аватарки на замовлення', callback_data='avaua')
Other = InlineKeyboardButton('Інші послуги', callback_data='otherua')
CategoriesUaIkb.add(Fortnite, Garant, Ava, Other)

OtherUaIkb = InlineKeyboardMarkup(row_width=1)
Spotify = InlineKeyboardButton('Spotify Premium', callback_data='spotifyua')
Youtube = InlineKeyboardButton('Youtube Premium', callback_data='ytua')
DiscordNitro = InlineKeyboardButton('Discord Nitro', callback_data='nitroua')
OtherLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='leftua')
OtherUaIkb.add(Spotify, DiscordNitro, Youtube, OtherLeft)

AvaUaIkb = InlineKeyboardMarkup(row_width=1)
Low = InlineKeyboardButton('Аватари низької якості', callback_data='avalowua')
Midl = InlineKeyboardButton('Аватарки середньої якості', callback_data='avamidlua')
Perfect = InlineKeyboardButton('Аватарки легендарної якості', callback_data='avalegua')
AvaLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='leftua')
AvaUaIkb.add(Low, Midl, Perfect, AvaLeft)

FortniteUaIkb = InlineKeyboardMarkup(row_width=1)
Codes = InlineKeyboardButton('🔑Ключі (коди) на скіни💁‍♂️', callback_data='codesua')
Gifts = InlineKeyboardButton('🎁Подарунки🎁', callback_data='giftsua')
Accaunt = InlineKeyboardButton('👤Аккаунти🧑‍🎤', callback_data='accua')
RandAccont = InlineKeyboardButton('🔀Рандом аккаунти🔄', callback_data='randaccua')
ObmenAccant = InlineKeyboardButton('🔄Обмін аккаунтів👤', callback_data='obmenaccua')
VBucks = InlineKeyboardButton('💸V-bucks на ваш аккаунт✅', callback_data='vbucksua')
Packs = InlineKeyboardButton('🍭Набори💼', callback_data='packsua')
FortniteLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='leftua')
FortniteUaIkb.add(Codes, Packs, VBucks, Gifts, Accaunt, ObmenAccant, RandAccont, FortniteLeft)

YouTubeUaIkb = InlineKeyboardMarkup(row_width=1)
YouTubeIndividual = InlineKeyboardButton('YouTube Individual || 90 грн', callback_data='indytua')
YouTubeFamily = InlineKeyboardButton('YouTube Family || 140 грн', callback_data='familyytua')
YouTubeStudent = InlineKeyboardButton('YouTube Student || 80 грн', callback_data='studentytua')
YouTubeLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='otherua')
YouTubeUaIkb.add(YouTubeIndividual, YouTubeFamily, YouTubeStudent, YouTubeLeft)

SpotifyUaIkb = InlineKeyboardMarkup(row_width=1)
SpotifyIndividual = InlineKeyboardButton('Spotify Individual || 120 грн', callback_data='indua')
SpotifyDuo = InlineKeyboardButton('Spotify Duo || 140 грн', callback_data='duoua')
SpotifyFamily = InlineKeyboardButton('Spotify Family || 150 грн', callback_data='familyua')
SpotifyLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='otherua')
SpotifyUaIkb.add(SpotifyIndividual, SpotifyDuo, SpotifyFamily, SpotifyLeft)

NitroUaIkb = InlineKeyboardMarkup(row_width=1)
NitroBasic30 = InlineKeyboardButton('Discord Nitro Basic 30 days|| 110 грн', callback_data='nbua30')
NitroBasic365 = InlineKeyboardButton('Discord Nitro Basic 365 days || 760 грн', callback_data='nbua365')
NitroFull30 = InlineKeyboardButton('Discord Nitro 30 days || 210 грн', callback_data='nua30')
NitroFull365 = InlineKeyboardButton('Discord Nitro 365 days || 1760 грн', callback_data='nua365')
NitroLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='otherua')
NitroUaIkb.add(NitroBasic30, NitroBasic365, NitroFull30, NitroFull365, NitroLeft)

ObmenAccantUaIkb = InlineKeyboardMarkup(row_width=1)
ObmenAccant12 = InlineKeyboardButton('Обмін аккаунтом 12 скінів', callback_data='obmenua12')
ObmenAccant15 = InlineKeyboardButton('Обмін аккаунтом 15 скінів', callback_data='obmenua15')
ObmenAccantLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='fortniteua')
ObmenAccantUaIkb.add(ObmenAccant12, ObmenAccant15, ObmenAccantLeft)

CodesUaIkb = InlineKeyboardMarkup(row_width=1)
code_1 = InlineKeyboardButton('Скін "Бетмен що сміється" || 260 грн', callback_data='buy_codeua_1')
code_2 = InlineKeyboardButton('Скін "Людина павук з епіцентру" || 135 грн', callback_data='buy_codeua_2')
code_3 = InlineKeyboardButton('Скін "Відроджена Харлі Квін" || 170 грн', callback_data='buy_codeua_3')
code_4 = InlineKeyboardButton('Інструмент "Крюк Жінки-кішки" || 245 грн', callback_data='buy_codeua_4')
code_5 = InlineKeyboardButton('Інструмент "Адамантеві кігті" || 95 грн', callback_data='buy_codeua_5')
code_6 = InlineKeyboardButton('Обгортка "Розробка Старка" || 95 грн', callback_data='buy_codeua_6')
code_7 = InlineKeyboardButton('Граффити "Ших! Ших!" || 95 грн', callback_data='buy_codeua_7')
code_8 = InlineKeyboardButton('Скін "Бетмен з епіцентру" || 230 грн', callback_data='buy_codeua_8')
code_9 = InlineKeyboardButton('Екран загрузки "Битва за епіцентр" || 95 грн', callback_data='buy_codeua_9')
CodesLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='fortniteua')
CodesUaIkb.add(code_1, code_2, code_3, code_8, code_4, code_5, code_6, code_7, code_9, CodesLeft)

GiftsUaIkb = InlineKeyboardMarkup(row_width=1)
gift_200 = InlineKeyboardButton('Подарунок на 200 V-Bucks || 25 грн', callback_data='buy_giftua_200')
gift_500 = InlineKeyboardButton('Подарунок на 500 V-Bucks || 55 грн', callback_data='buy_giftua_500')
gift_800 = InlineKeyboardButton('Подарунок на 800 V-Bucks || 80 грн', callback_data='buy_giftua_800')
gift_1200 = InlineKeyboardButton('Подарунок на 1200 V-Bucks || 125 грн', callback_data='buy_giftua_1200')
gift_1500 = InlineKeyboardButton('Подарунок на 1500 V-Bucks || 160 грн', callback_data='buy_giftua_1500')
gift_1800 = InlineKeyboardButton('Подарунок на 1800 V-Bucks || 185 грн', callback_data='buy_giftua_1800')
gift_2000 = InlineKeyboardButton('Подарунок на 2000 V-Bucks || 210 грн', callback_data='buy_giftua_2000')
gift_2500 = InlineKeyboardButton('Подарунок на 2500 V-Bucks || 260 грн', callback_data='buy_giftua_2500')
gift_3000 = InlineKeyboardButton('Подарунок на 3000 V-Bucks || 310 грн', callback_data='buy_giftua_3000')
GiftsLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='fortniteua')
GiftsUaIkb.add(gift_200, gift_500, gift_800, gift_1200, gift_1500, gift_1800, gift_2000, gift_2500, gift_3000, GiftsLeft)

AccUaIkb = InlineKeyboardMarkup(row_width=1)
Acc70 = InlineKeyboardButton('Аккаунт 70 скінів || 430 грн', callback_data='acc70')
Acc33 = InlineKeyboardButton('Аккаунт 33 скіна || 150 грн', callback_data='acc33')
AccLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='fortniteua')
AccUaIkb.add(Acc70, Acc33, AccLeft) 

RandAccUaIkb = InlineKeyboardMarkup(row_width=1)
Rand_acc_25 = InlineKeyboardButton('Рандом дешевий || 25 грн', callback_data='rand_accua_25')
Rand_acc_65 = InlineKeyboardButton('Рандом середній || 65 грн', callback_data='rand_accua_65')
Rand_acc_120 = InlineKeyboardButton('Рандом дорогий || 120 грн', callback_data='rand_accua_120')
RandAccLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='fortniteua')
RandAccUaIkb.add(Rand_acc_25, Rand_acc_65, Rand_acc_120, RandAccLeft)

VBucksUaIkb = InlineKeyboardMarkup(row_width=1)
VBucks1000 = InlineKeyboardButton('1 000 V-Bucks || 105 грн', callback_data='vbua1000')
VBucks2800 = InlineKeyboardButton('2 800 V-Bucks || 230 грн', callback_data='vbua2800')
VBucks5000 = InlineKeyboardButton('5 000 V-Bucks || 345 грн', callback_data='vbua5000')
VBucks13500 = InlineKeyboardButton('13 500 V-Bucks || 770 грн', callback_data='vbua13500')
VBucksLeft = InlineKeyboardButton('⬅ Повернутися ↩', callback_data='fortniteua')
VBucksUaIkb.add(VBucks1000, VBucks2800, VBucks5000, VBucks13500, VBucksLeft)

PacksUaIkb = InlineKeyboardMarkup(row_width=1)
Bioluminescens = InlineKeyboardButton('Набір завдань "Біолюмінесценція" || 120 грн', callback_data='bioluminescensua')
TemnuyOgon = InlineKeyboardButton('Комплект "Темний вогонь" || 190 грн', callback_data='temnyogonua')
Orysheynica = InlineKeyboardButton('Набір "Зброярниця Кліп" || 200 грн', callback_data='orysheynicaua')
PrysrakLegend = InlineKeyboardButton('Набір "Легенди привидів" || 235 грн', callback_data='prysraklegendua')
KorolyAndVoins = InlineKeyboardButton('Набір "Королі і воїни" || 250 грн', callback_data='korolyandvoinsua')
Otrad = InlineKeyboardButton('Підписка Загін Fortnite || 240 грн', callback_data='otradua')
PacksLeft = InlineKeyboardButton('⬅ Вернуться ↩', callback_data='fortniteua')
PacksUaIkb.add(Bioluminescens, TemnuyOgon, Orysheynica, PrysrakLegend, KorolyAndVoins, Otrad, PacksLeft)

BuyAccUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купити товар', callback_data='buyua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='accua')
BuyAccUaIkb.add(BuyBut, LeftBut)

BuyRandomUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купити товар', callback_data='buyua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='randaccua')
BuyRandomUaIkb.add(BuyBut, LeftBut)

BuyGiftUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купити товар', callback_data='buyua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='giftsua')
BuyGiftUaIkb.add(BuyBut, LeftBut)


BuyObmenUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='🔄 Обміняти аккаунт', callback_data='obmenua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='obmenaccua')
BuyObmenUaIkb.add(BuyBut, LeftBut)

BuyCodeUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купити товар', callback_data='buyua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='codesua')
BuyCodeUaIkb.add(BuyBut, LeftBut)

BuySpotifyUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купити товар', callback_data='buyua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='spotifyua')
BuySpotifyUaIkb.add(BuyBut, LeftBut)

BuyYtUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купити товар', callback_data='buyua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='ytua')
BuyYtUaIkb.add(BuyBut, LeftBut)

BuyNitroUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купити товар', callback_data='buyua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='nitroua')
BuyNitroUaIkb.add(BuyBut, LeftBut)

BuyVbUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купити товар', callback_data='buyua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='vbucksua')
BuyVbUaIkb.add(BuyBut, LeftBut)

BuyPacksUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Купити товар', callback_data='buyua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='packsua')
BuyPacksUaIkb.add(BuyBut, LeftBut)

BuyAvaUaIkb = InlineKeyboardMarkup(row_width=1)
BuyBut = InlineKeyboardButton(text='💰 Замовити Аватарку', callback_data='zakazua')
LeftBut = InlineKeyboardButton(text='⬅ Повернутися ↩', callback_data='avaua')
BuyAvaUaIkb.add(BuyBut, LeftBut)

Language = InlineKeyboardMarkup(row_width=1)
Ua = InlineKeyboardButton(text='🇺🇦Український магазин🇺🇦', callback_data='ua')
Ru = InlineKeyboardButton(text='🇷🇺Русский магазин🇷🇺', callback_data='ru')
Language.add(Ua, Ru)